### ISSUE TITLE
An error message appears after clicking on the "Upload video" button

### ISSUE THREAD

**Issue by ralede** [opencast-ilias/OpencastPageComponent#10]
**Describe the bug**
An error message appears after clicking on the "Upload video" button.

**To Reproduce**
1. Go to 'OpencastPageComponent Editor'
2. Click on 'Upload New Video'
3. See error

**Expected behavior**
Input screen for video upload

**Screenshots**
1)
![Bild1](https://user-images.githubusercontent.com/118901635/206450917-b056eaec-fce5-46e7-bf7f-d34067b2578f.jpg)

2)
![Bild2](https://user-images.githubusercontent.com/118901635/206450936-e03e404f-5dee-4ca5-988d-aa45aeda04a2.jpg)

**Log**
[cc7c0_2578.log](https://github.com/opencast-ilias/OpencastPageComponent/files/10185509/cc7c0_2578.log)

**Environment (please complete the following information):**
 - ILIAS version: [7.16]
 - PHP version: [PHP 7.3.31]
 - Plugin version: v1.7.1
 - Browser: [chrome, firefox]
 - Opencast 12.0.0

**Comment by dagraf** [comment]
@ralede: Can you please test the PR https://github.com/opencast-ilias/OpencastPageComponent/pull/11 fixing this issue and post your results here? Thx!
