### ISSUE TITLE
OpencastPageComponent Plugin prevents refreshing all languages globally

### ISSUE THREAD

**Issue by ckozianka** [opencast-ilias/OpencastPageComponent#13]
OpencastPageComponent Plugin prevents refreshing all languages globally and throws a Whoops error.

1. Make sure OpencastPageComponent plugin is active.
2. Go to Administration > System settings and Maintenance > Languages.
3. Click on "Refresh all languages".
4. See error below.

```
Whoops\Exception\ErrorException thrown with message "Class srag\DIC\OpencastPageComponent\Database\DatabaseDetector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ilDBInterface::primaryExistsByFields)"

Stacktrace:
#2 Whoops\Exception\ErrorException in /var/www/ilias/Customizing/global/plugins/Services/COPage/PageComponent/OpencastPageComponent/vendor/srag/dic/src/Database/DatabaseDetector.php:21
#1 Whoops\Run:handleError in /var/www/ilias/libs/composer/vendor/filp/whoops/src/Whoops/Run.php:514
#0 Whoops\Run:handleShutdown in [internal]:0

```

**Environment**
 - ILIAS version: v7.26 2023-10-23
 - PHP version: 7.3.31-1~deb10u5
 - Plugin version: 1.7.1

**Comment by reiferschris** [comment]
We ran into the same issue.

**Comment by dagraf** [comment]
After pulling https://github.com/opencast-ilias/OpencastPageComponent/pull/12 this issue does not appear anymore on our installations. 

@ckozianka: Could you please also test this PR and report your results here? Thx!

**Comment by ckozianka** [comment]
Sorry, I was too  busy. I can confirm that this issue has been fixed. Thank you!
