### ISSUE TITLE
Fatal error on install of release_8 branch of OpencastPageComponent

### ISSUE THREAD

**Issue by gvollbach** [opencast-ilias/OpencastPageComponent#25]
When trying to install the plugin, from branch release_8, following error occurs:

`Call to undefined method srag\Plugins\OpencastPageComponent\Config\Config::updateDB()`

StackTrace:

`
Stack frames (13)
12
Error 
/var/www/projekte/1_dev/8_0/8_0/Services/Database/classes/class.ilDBUpdate.php396
11
 eval
/var/www/projekte/1_dev/8_0/8_0/Services/Database/classes/class.ilDBUpdate.php396
10
ilDBUpdate applyUpdateNr
/var/www/projekte/1_dev/8_0/8_0/Services/Database/classes/class.ilDBUpdate.php316
9
ilDBUpdate applyUpdate
/var/www/projekte/1_dev/8_0/8_0/Services/Component/classes/class.ilPlugin.php311
8
ilPlugin updateDatabase
/var/www/projekte/1_dev/8_0/8_0/Services/Component/classes/class.ilPlugin.php283
7
ilPlugin update
/var/www/projekte/1_dev/8_0/8_0/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php176
6
ilObjComponentSettingsGUI update
/var/www/projekte/1_dev/8_0/8_0/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php170
5
ilObjComponentSettingsGUI installPlugin
/var/www/projekte/1_dev/8_0/8_0/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php124
4
ilObjComponentSettingsGUI executeCommand
/var/www/projekte/1_dev/8_0/8_0/Services/UICore/classes/class.ilCtrl.php199
3
ilCtrl forwardCommand
/var/www/projekte/1_dev/8_0/8_0/Services/Administration/classes/class.ilAdministrationGUI.php237
2
ilAdministrationGUI executeCommand
/var/www/projekte/1_dev/8_0/8_0/Services/UICore/classes/class.ilCtrl.php199
1
ilCtrl forwardCommand
/var/www/projekte/1_dev/8_0/8_0/Services/UICore/classes/class.ilCtrl.php174
0
ilCtrl callBaseClass
/var/www/projekte/1_dev/8_0/8_0/ilias.php24

`

**Comment by dagraf** [comment]
@chfsx: Can you please have a look at this issue? Guido needs the OpencastPagecomponent-Plugin integrate Opencast videos in the plugin "Interactive Video". Thx!

**Comment by chfsx** [comment]
@gvollbach I made a fix in #26, could you please test if this resolves the issue?

**Comment by gvollbach** [comment]
@chfsx Thx, seems to work with your fixes.

**Comment by chfsx** [comment]
Thanks for the feedback, I released a new version 8.0.1
