### ISSUE TITLE
Release 7 & 8: Deselection columns has no effect when inserting a video

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpencastPageComponent#27]
**Describe the bug**
Deselection of shown columns has no effect. After clicking on "Refresh", all columns are still shown and when opening the associated modal the columns that should not appear anymore are still selected.

**To Reproduce**
1. Insert a Opencast video using the page editor (Customise page > + > Insert Opencast Video)
2. Click on 'Columns'
3. Deactivate one ore more of the columns an hit on 'Refresh'
4. See that all columns still get shown
5. Click on 'Columns' again > See tat all collumns are still selected

**Expected behavior**
When selecting columns they should not appear anymore in the table.

**Screenshots**

Before clicking "Refresh"
<img width="888" alt="Bildschirmfoto 2024-03-25 um 14 53 10" src="https://github.com/opencast-ilias/OpencastPageComponent/assets/15246287/84018efb-caa1-4ece-9d35-288af04ab480">

After clicking "Refresh"
<img width="881" alt="Bildschirmfoto 2024-03-25 um 14 53 20" src="https://github.com/opencast-ilias/OpencastPageComponent/assets/15246287/efc43322-080d-49a7-9888-5a3d0d859d99">

**Environment (please complete the following information):**
 - ILIAS version: v7.26 2023-10-2 AND v8.9 2024-02-14
 - Plugin version: OpencastPageComponent = 7.0.1 AND 8.0.0; OpenCast = 7.0.0 AND 8.0.2
 - Browser: Firefox

**Additional context**
Bug appears in release_7 and release_8.

**Comment by dagraf** [comment]
@chfsx: Could you please take a look at this bug and fix it if possible? Thx!

**Comment by rfcmaXi** [comment]
If it is useful: I can confirm the error with the OC plugin version v8.1.3 and the current PageComponent version :)

**Comment by dagraf** [comment]
With https://github.com/opencast-ilias/OpencastPageComponent/pull/28 there are no longer selectable columns for the moment (this could be possible in a future version again). Therefore, I close this issue. Feel free to open a new issue if you would want the columns to be selectable again.
