### ISSUE TITLE
All dates are set to 1970

### ISSUE THREAD

**Issue by ebbertd** [opencast-ilias/OpencastPageComponent#5]
Using the current version in the main branch (1.6.2) all start dates are displayed as `01.01.1970 01:00`. See screenshot.

Plugin version: 1.6.2
ILIAS version: v6.15 2022-02-02
PHP version: 7.4.3

![Screenshot 2022-04-29 at 09-04-48 ILIAS bla](https://user-images.githubusercontent.com/20522234/165899364-da189b54-1df1-40db-ab21-8e5dbe1e839a.png)

**Comment by dagraf** [comment]
@okaufman I  can only partly reproduce this issue:

- It does appear on our Community-ILIAS (ILIAS: v7.12 2022-07-29).
- It does NOT appear on our ILIAS-Next (ILIAS: v7.11 2022-06-2).
